version: 3.9

services:
  vite:
    container_name: vite-container
    image: node:17-stretch
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/node/workspace
      - node_modules:/home/node/workspace/node_modules
