version: "3.9"

services:
  vite:
    container_name: vite-container
    image: vite-container
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/node/workspace
      - node_modules:/home/node/workspace/node_modules
    networks:
      - dev_net

volumes:
  node_modules:
  vendor:

networks:
  dev_net:
